apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-finchley
  namespace: finchley
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/finchley"